name: Build Windows release binaries (v2)
on:
  release:
    types:
      - edited
      - published
  push:
    branches:
      - master
    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Get Latest Release
      uses: pozetroninc/github-action-get-latest-release@v0.3.0
      with:
        owner: bloodsplatter
        repo: BomFinder
      id: version
    - name: Get code
      uses: actions/checkout@v2
      with:
        ref: ${{steps.version.outputs.release}}
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.201
    - name: Build Windows
      run: dotnet build --configuration Release --runtime win10-x64
    - name: Set Base Path
      run: echo "::set-env name=build_path::'$GITHUB_WORKSPACE/BomFinder/bin/Release/netcoreapp3.1'"
    - name: Set Windows Release Path
      run: echo "::set-env name=win_release_path::$BUILD_PATH/win10-x64"
    - name: Zip Windows Release
      run: 7z a $FILE $DIRECTORY
      env:
        FILE: BomFinder-${{steps.version.outputs.release}}-windows10-x64.zip
        DIRECTORY: $WIN_RELEASE_PATH
      id: windows_zip
    - name: Upload files to a GitHub release
      uses: svenstaro/upload-release-action@1.0.1
      with:
        repo_token: ${{secrets.GITHUB_TOKEN}}
        tag: ${{steps.version.outputs.release}}
        file: $GITHUB_WORKSPACE/BomFinder-${{steps.version.outputs.release}}-windows10-x64.zip
